BOARD_WIDTH = 60
BOARD_HEIGHT = 30

PLAYER_ICON = "🧙"
PLAYER_START_X = 3
PLAYER_START_Y = 3
PLAYER_HP = 5
PLAYER_EXPERIENCE = 0
PLAYER_MAX_EXPERIENCE = 100
PLAYER_MAX_HP = 5
PLAYER_ATTACK = 1
PLAYER_LV = 1

WALL = "⬜"
PATH = "⬛"

ENEMY_LVL_1_ICON = "🐁"
ENEMY_LVL_1_HP = 2
ENEMY_LVL_1_EXPERIENCE = 10
ENEMY_LVL_1_ATTACK = 2

ENEMY_LVL_2_ICON = "🦟"
ENEMY_LVL_2_HP = 4
ENEMY_LVL_2_EXPERIENCE = 20
ENEMY_LVL_2_ATTACK = 3

BOSS_ICON = "🐸"
BOSS_HP = 5
BOSS_EXPERIENCE = 50
BOSS_ATTACK = 4

ITEM_WATERMELON_ICON = "🍉"
ITEM_WATERMELON_ADD_HP = 2
ITEM_WATERMELON_EXPERIENCE = 10
ITEM_WATERMELON_ATTACK = 0

ITEM_APPLE_ICON = "🍎"
ITEM_APPLE_ADD_HP = 4
ITEM_APPLE_EXPERIENCE = 10
ITEM_APPLE_ATTACK = 0

ITEM_BANANA_ICON = "🍌"
ITEM_BANANA_ADD_HP = 0
ITEM_BANANA_EXPERIENCE = 20
ITEM_BANANA_ATTACK = 0

ITEM_KNIFE_ICON = "🔪"
ITEM_KNIFE_ADD_HP = 0
ITEM_KNIFE_EXPERIENCE = 0
ITEM_KNIFE_ATTACK = 1


ITEM_MEDICINE_ICON = "🧿"
MEDICINE_MAX_HP = 1
MEDICINE_EXPERIENCE = 0
MEDICINE_ATTACK = 0
